version: "3"

services:
  express:
    image: node:lts
    tty: true
    expose:
      - 9229
      - 3001
      - 5555
    ports:
      - 9229:9229
      - 3001:3000
      - 5555:5555
    volumes:
      - ./:/src
    working_dir: "/src/server"
    command: npm run start:debug

  mysql:
    build: ./database/dockerfile
    platform: linux/x86_64
    expose:
      - 3306
    volumes:
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306

  next:
    image: node:lts
    tty: true
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./:/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    working_dir: "/src/front"